FROM bitnami/spark:3.2.1

RUN curl -o $SPARK_HOME/jars/mongo-spark-connector_2.12-3.1.2.jar https://repo1.maven.org/maven2/org/mongodb/spark/mongo-spark-connector_2.12/3.1.2/mongo-spark-connector_2.12-3.1.2.jar
